spring:
  mail:
    host: smtp.elasticemail.com
    port: 2525
    username: gene.zagalsky@gmail.com
    password: 10F208B0912BEEA3427A31C7D13568628591
    properties:
      mail:
        transport:
          protocol: smtp
        debug: true
        smtp:
          auth: true
          starttls:
            enable: true